# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-02 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20171202_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionaryclass',
            options={'verbose_name': 'Dictionary class', 'verbose_name_plural': 'Dictionary classes'},
        ),
    ]
