version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: boto3
    versions:
    - 1.16.62
    - 1.17.11
    - 1.17.16
    - 1.17.2
    - 1.17.21
    - 1.17.26
    - 1.17.32
    - 1.17.38
    - 1.17.43
    - 1.17.48
    - 1.17.53
    - 1.17.6
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: tqdm
    versions:
    - 4.56.0
    - 4.56.2
    - 4.57.0
    - 4.58.0
    - 4.59.0
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: pylint
    versions:
    - 2.6.2
    - 2.7.1
    - 2.7.2
  - dependency-name: sentry-sdk
    versions:
    - 0.19.5
    - 0.20.0
    - 0.20.3
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pylint-django
    versions:
    - 2.4.2
  - dependency-name: django-debug-toolbar
    versions:
    - "3.2"
  - dependency-name: lxml
    versions:
    - 4.6.2
  - dependency-name: pytest-django
    versions:
    - 4.1.0
  - dependency-name: django-simple-history
    versions:
    - 2.12.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.9
