# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 00:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='last_reviewed_log',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 18, 31, 33, 690980)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 18, 31, 33, 690980)),
        ),
    ]
