# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 23:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_manager', '0002_auto_20171017_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appdata',
            options={'permissions': (('can_view', 'Can view the app log data'),)},
        ),
        migrations.AlterField(
            model_name='appdata',
            name='review_day',
            field=models.CharField(blank=True, default='*', help_text='The day of the month to update on (1-31)', max_length=100, null=True, validators=[django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='review_hour',
            field=models.CharField(blank=True, default='*', help_text='The hour of the day to update on (0 = midnight)', max_length=100, null=True, validators=[django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='review_minute',
            field=models.CharField(blank=True, default='*', help_text='The minutes of an hour to update on', max_length=100, null=True, validators=[django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='review_month',
            field=models.CharField(blank=True, default='*', help_text='The month to update on (1 = January, 12 = December)', max_length=100, null=True, validators=[django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='review_weekday',
            field=models.CharField(blank=True, default='*', help_text='The weekday to update on (0 = Sunday, 6 = Saturday)', max_length=100, null=True, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
