# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_manager', '0004_auto_20171019_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='level_no',
        ),
    ]
