# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_manager', '0005_remove_logentry_level_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='level_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
