# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 02:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_manager', '0006_auto_20171016_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='last_reviewed_log',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 20, 16, 20, 574434)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 20, 16, 20, 574434)),
        ),
    ]
