# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 03:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_manager', '0007_auto_20171016_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='last_reviewed_log',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 21, 33, 40, 809961)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 21, 33, 40, 809961)),
        ),
    ]
