# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_manager', '0009_appdata_asc_time_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='created',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
