# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_manager', '0010_auto_20171023_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='relative_created',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
