# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hc_dpd', '0005_auto_20171120_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCompanyType',
        ),
        migrations.DeleteModel(
            name='SubCompanyTypePend',
        ),
    ]
