# Generated by Django 3.2.12 on 2022-04-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_dpd', '0015_update_names_and_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpdchecksum',
            name='checksum',
            field=models.CharField(blank=True, default='a', help_text='The checksum value for the specified items.', max_length=10),
            preserve_default=False,
        ),
    ]
