language: python
sudo: required
dist: xenial
services:
  - postgresql
python:
  - 3.7
install:
  - pip install pipenv codecov
  - pipenv run python -m pip install -U pip
  - pipenv install --dev --ignore-pipfile
before_script:
  - cp config/settings/.study_buffalo.env config/settings/study_buffalo.env
  - psql -c "CREATE DATABASE study_buffalo;" -U postgres
  - psql -c "CREATE USER study_buffalo WITH PASSWORD 'study_buffalo';" -U postgres
  - psql -c "ALTER ROLE study_buffalo SET client_encoding TO 'utf8';" -U postgres
  - psql -c "ALTER ROLE study_buffalo SET default_transaction_isolation TO 'read committed';" -U postgres
  - psql -c "ALTER ROLE study_buffalo SET timezone TO 'UTC';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE study_buffalo TO study_buffalo;" -U postgres
  - psql -c "ALTER USER study_buffalo CREATEDB;" -U postgres
  - pipenv run python manage.py collectstatic --no-input
script:
  - pipenv run pytest --cov qlinicalrx_app --cov-report xml
after_success:
  - codecov
