language: python
sudo: required
dist: xenial
services:
  - postgresql
python:
  - 3.7
install:
  - pip install pipenv codecov
  # Temporary: some python versions & pip 18.1 have issues with pipenv
  - pipenv run python -m pip install -U pip
  - pipenv install --dev --ignore-pipfile
before_script:
  - mkdir ../config
  - cp config.env ../config/study_buffalo.env
  - psql -c 'CREATE DATABASE studybuffalo;'-U postgres
  - psql -c 'CREATE USER studybuffalo WITH PASSWORD studybuffalo;'-U postgres
  - psql -c 'ALTER ROLE studybuffalo SET client_encoding TO 'utf8';'-U postgres
  - psql -c 'ALTER ROLE studybuffalo SET default_transaction_isolation TO 'read committed';'-U postgres
  - psql -c 'ALTER ROLE studybuffalo SET timezone TO 'UTC';'-U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE studybuffalo TO studybuffalo;'-U postgres
script:
  - pipenv run coverage run manage.py test
after_success:
  - codecov
