language: python
sudo: required
dist: xenial
python:
  - 3.7
install:
  - pip install pipenv codecov
  # Temporary: some python versions & pip 18.1 have issues with pipenv
  - pipenv run python -m pip install -U pip
  - pipenv install --dev --ignore-pipfile
before_script:
  - mkdir ../config
  - cp config.env ../config/study_buffalo.env
script:
  - pipenv run coverage run manage.py test
after_success:
  - codecov
