version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    ports:
      - "5432:5432"
  web:
    build: .
    depends_on:
      - db
