# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 04:09
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the application to be monitored', max_length=256)),
                ('log_location', models.CharField(help_text='Absolute directory containing the log file(s)', max_length=512)),
                ('file_name', models.CharField(help_text='Regex expression that matches the log file name(s)', max_length=512)),
                ('flag_start', models.CharField(blank=True, help_text='Text located in the log file that notes the application has started properly', max_length=512, null=True)),
                ('flag_end', models.CharField(blank=True, help_text='Text located in the log file that notes the application has finished properly', max_length=512, null=True)),
                ('review_minute', models.PositiveSmallIntegerField(blank=True, help_text='The minutes of an hour to update on', null=True, validators=[django.core.validators.MaxValueValidator(59)])),
                ('review_hour', models.PositiveSmallIntegerField(blank=True, help_text='The hour of the day to update on (0 = midnight)', null=True, validators=[django.core.validators.MaxValueValidator(59)])),
                ('review_day', models.PositiveSmallIntegerField(blank=True, help_text='The day of the month to update on (1-31)', null=True, validators=[django.core.validators.MaxValueValidator(59)])),
                ('review_month', models.PositiveSmallIntegerField(blank=True, help_text='The month to update on (1 = January, 12 = December)', null=True, validators=[django.core.validators.MaxValueValidator(59)])),
                ('review_weekday', models.PositiveSmallIntegerField(blank=True, help_text='The weekday to update on (0 = Sunday, 6 = Saturday)', null=True, validators=[django.core.validators.MaxValueValidator(6)])),
                ('next_review', models.DateTimeField(default=datetime.datetime(2017, 10, 16, 17, 37, 53, 589581))),
                ('last_reviewed_log', models.DateTimeField(default=datetime.datetime(2017, 10, 16, 17, 37, 53, 589581))),
                ('last_review', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asc_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.TimeField(blank=True, null=True)),
                ('exc_info', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=512, null=True)),
                ('func_name', models.CharField(blank=True, max_length=512, null=True)),
                ('level_name', models.CharField(blank=True, max_length=512, null=True)),
                ('level_no', models.CharField(blank=True, max_length=512, null=True)),
                ('line_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('module', models.CharField(blank=True, max_length=512, null=True)),
                ('msecs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('path_name', models.CharField(blank=True, max_length=512, null=True)),
                ('process', models.CharField(blank=True, max_length=512, null=True)),
                ('process_name', models.CharField(blank=True, max_length=512, null=True)),
                ('relative_created', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stack_info', models.TextField(blank=True, null=True)),
                ('thread', models.CharField(blank=True, max_length=512, null=True)),
                ('thread_name', models.CharField(blank=True, max_length=512, null=True)),
                ('app_name', models.ForeignKey(help_text='The app this entry is for', on_delete=django.db.models.deletion.CASCADE, to='log_manager.AppData')),
            ],
        ),
        migrations.AlterField(
            model_name='appdata',
            name='last_reviewed_log',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 18, 31, 33, 690980)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 18, 31, 33, 690980)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='last_reviewed_log',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 19, 15, 14, 153622)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 19, 15, 14, 153622)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='last_reviewed_log',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 19, 15, 51, 57655)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 19, 15, 51, 57655)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='last_reviewed_log',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 19, 22, 5, 781126)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 19, 22, 5, 781126)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='last_reviewed_log',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 20, 15, 1, 560050)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 20, 15, 1, 560050)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='last_reviewed_log',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 20, 16, 20, 574434)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 20, 16, 20, 574434)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='last_reviewed_log',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 21, 33, 40, 809961)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 21, 33, 40, 809961)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='last_reviewed_log',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 4, 6, 19, 360489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 4, 6, 19, 360489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='last_reviewed_log',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 4, 7, 12, 177808, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 4, 7, 12, 177808, tzinfo=utc)),
        ),
    ]
