# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_manager', '0001_squashed_0010_auto_20171016_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='last_reviewed_log',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
