# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hc_dpd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubAHFS',
        ),
        migrations.DeleteModel(
            name='SubAHFSPend',
        ),
    ]
