# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_dpd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugproduct',
            name='drug_product_class',
        ),
        migrations.AddField(
            model_name='drugproduct',
            name='class_e',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='drugproduct',
            name='drug_identification_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='packaging',
            name='package_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='company_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='pharm_form_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inactiveproducts',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inactiveproducts',
            name='drug_identification_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='inactiveproducts',
            name='history_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='package_size_unit',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_of_administration_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='history_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
