# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_dpd', '0002_auto_20171119_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='pharmaceutical_form_f',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
