# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_dpd', '0003_auto_20171119_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_of_administration_f',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
