# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_dpd', '0004_auto_20171119_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
