# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_dpd', '0005_auto_20171119_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeingredients',
            name='ingredient_f',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
