# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_dpd', '0006_auto_20171119_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeingredients',
            name='ingredient_f',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
