# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hc_dpd', '0007_auto_20171119_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugproduct',
            old_name='late_update_date',
            new_name='last_update_date',
        ),
    ]
