# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_dpd', '0008_auto_20171119_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAHFS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=80)),
                ('substitution', models.CharField(max_length=80)),
            ],
        ),
    ]
