# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hc_dpd', '0009_subahfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAHFSPend',
            fields=[
                ('subahfs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hc_dpd.SubAHFS')),
            ],
            bases=('hc_dpd.subahfs',),
        ),
    ]
