# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='guide_type',
            field=models.CharField(choices=[('d', 'Document'), ('h', 'HTML')], default='d', help_text='The format the guide is saved as; MUST match which guide (document or HTML) is uploaded', max_length=1),
        ),
    ]
