# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20170828_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='guide_type',
        ),
    ]
