# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_price_calculator', '0005_auto_20170919_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendgeneric',
            name='correction',
            field=models.CharField(max_length=175),
        ),
        migrations.AlterField(
            model_name='pendgeneric',
            name='original',
            field=models.CharField(max_length=175, unique=True),
        ),
    ]
