# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(help_text='Optional background image for the slide', upload_to='home/carousel/')),
                ('html', models.TextField(blank=True, help_text='Any HTML to accompany the carousel slide')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Date to start displaying the slide')),
                ('end_date', models.DateField(blank=True, help_text='Date to stop display the slide (leave blank for no end date)')),
                ('priority', models.SmallIntegerField(default=1, help_text='The priority order to show the slide')),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
                'ordering': ['priority', 'start_date'],
            },
        ),
    ]
