# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date to stop display the slide (leave blank for no end date)', null=True),
        ),
    ]
