# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_auto_20170828_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='background',
            field=models.ImageField(blank=True, help_text='Optional background image for the slide', null=True, upload_to='home/carousel/'),
        ),
    ]
