# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExcludedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('dictionary_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.DictionaryType')),
            ],
        ),
        migrations.CreateModel(
            name='ExcludedWordPending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('dictionary_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.DictionaryType')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('dictionary_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.DictionaryType')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('monitored_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.MonitoredApplication')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('dictionary_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.DictionaryType')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.Language')),
            ],
        ),
        migrations.CreateModel(
            name='WordPending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('dictionary_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.DictionaryType')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.Language')),
            ],
        ),
        migrations.AddField(
            model_name='monitoredfield',
            name='monitored_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.MonitoredModel'),
        ),
        migrations.AddField(
            model_name='excludedwordpending',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.Language'),
        ),
        migrations.AddField(
            model_name='excludedword',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.Language'),
        ),
    ]
