# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_squashed_0002_update_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
