# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='The name of the category', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='playitem',
            name='alt_text',
            field=models.CharField(help_text='Text to show on cursor hover over the item', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='playitem',
            name='description',
            field=models.TextField(default='', help_text='Any additional text to include on served page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playitem',
            name='location',
            field=models.CharField(default='', help_text='The file name or URL where the item can be accessed', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unqiue ID for this item', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playitem',
            name='type',
            field=models.CharField(choices=[('a', 'Audio'), ('i', 'Image'), ('u', 'URL'), ('v', 'Video')], help_text='The file type of the item', max_length=1),
        ),
        migrations.AddField(
            model_name='playitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.Category'),
        ),
    ]
