# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20170827_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playitem',
            name='description',
            field=models.TextField(help_text='Any additional text to include on served page', null=True),
        ),
    ]
