# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_auto_20170828_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playimage',
            old_name='location',
            new_name='original_image',
        ),
        migrations.AddField(
            model_name='playimage',
            name='resized_image',
            field=models.ImageField(default='', editable=False, upload_to='play/images/resized/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playaudio',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Any additional text to display below the image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playaudio',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.PlayPage'),
        ),
        migrations.AlterField(
            model_name='playaudio',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title to display above the audio player', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playimage',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='Text to show on cursor hover over the item', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playimage',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Any additional text to display below the image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playimage',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.PlayPage'),
        ),
        migrations.AlterField(
            model_name='playimage',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title to display above the image', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the play item was release'),
        ),
    ]
