# Generated by Django 2.2.3 on 2019-07-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitutions', '0004_auto_20171120_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelfields',
            options={'verbose_name': 'Model Field', 'verbose_name_plural': 'Model Fields'},
        ),
    ]
