# Generated by Django 2.2.3 on 2019-07-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug_price_calculator', '0005_update_sub_and_pend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='clients',
        ),
        migrations.AddField(
            model_name='clients',
            name='price',
            field=models.OneToOneField(blank=True, help_text='The price details these clients apply to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug_price_calculator.Price'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_1',
            field=models.CharField(max_length=7, null=True, verbose_name='ATC level 1 code'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_1_text',
            field=models.CharField(max_length=200, null=True, verbose_name='ATC level 1 description'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_2',
            field=models.CharField(max_length=7, null=True, verbose_name='ATC level 2 code'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_2_text',
            field=models.CharField(max_length=200, null=True, verbose_name='ATC level 2 description'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_3',
            field=models.CharField(max_length=7, null=True, verbose_name='ATC level 3 code'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_3_text',
            field=models.CharField(max_length=200, null=True, verbose_name='ATC level 3 description'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_4',
            field=models.CharField(max_length=7, null=True, verbose_name='ATC level 4 code'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_4_text',
            field=models.CharField(max_length=200, null=True, verbose_name='ATC level 4 description'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='atc',
            field=models.ForeignKey(blank=True, help_text='The ATC code for this drug', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs', to='drug_price_calculator.ATC', verbose_name='ATC'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='din',
            field=models.CharField(help_text="The drug's DIN/NPN/PIN", max_length=8, unique=True, verbose_name='DIN'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='ptc',
            field=models.ForeignKey(blank=True, help_text='The PTC code for this drug', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs', to='drug_price_calculator.PTC', verbose_name='PTC'),
        ),
        migrations.AlterField(
            model_name='price',
            name='abc_id',
            field=models.PositiveIntegerField(help_text='The Alberta Blue Cross iDBL ID number', verbose_name='ABC ID'),
        ),
        migrations.AlterField(
            model_name='price',
            name='lca_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The Least Cost Alternative price (in CAD)', max_digits=10, null=True, verbose_name='LCA price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='mac_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The Maximum Allowable Cost price (in CAD)', max_digits=10, null=True, verbose_name='MAC price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='mac_text',
            field=models.CharField(blank=True, help_text='Descriptions for the MAC pricing', max_length=150, null=True, verbose_name='MAC text'),
        ),
        migrations.AlterField(
            model_name='price',
            name='unit_issue',
            field=models.CharField(blank=True, help_text='The unit of issue for pricing', max_length=25, null=True, verbose_name='unit of issue'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_1',
            field=models.CharField(max_length=11, null=True, verbose_name='PTC level 1 code'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_1_text',
            field=models.CharField(max_length=75, null=True, verbose_name='PTC level 1 description'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_2',
            field=models.CharField(max_length=11, null=True, verbose_name='PTC level 2 code'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_2_text',
            field=models.CharField(max_length=75, null=True, verbose_name='PTC level 2 description'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_3',
            field=models.CharField(max_length=11, null=True, verbose_name='PTC level 3 code'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_3_text',
            field=models.CharField(max_length=75, null=True, verbose_name='PTC level 3 description'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_4',
            field=models.CharField(max_length=11, null=True, verbose_name='PTC level 4 code'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_4_text',
            field=models.CharField(max_length=75, null=True, verbose_name='PTC level 4 description'),
        ),
    ]
