# Generated by Django 2.2.3 on 2019-07-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_price_calculator', '0009_auto_20190713_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='generic_product',
            field=models.CharField(blank=True, help_text='A calculated name to identify similar drugs', max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_1',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='ATC level 1 code'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_1_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ATC level 1 description'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_2',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='ATC level 2 code'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_2_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ATC level 2 description'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_3',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='ATC level 3 code'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_3_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ATC level 3 description'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_4',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='ATC level 4 code'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_4_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ATC level 4 description'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_5',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='ATC level 5 code'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='atc_5_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ATC level 5 description'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_1',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='PTC level 1 code'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_1_text',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='PTC level 1 description'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_2',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='PTC level 2 code'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_2_text',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='PTC level 2 description'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_3',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='PTC level 3 code'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_3_text',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='PTC level 3 description'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_4',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='PTC level 4 code'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc_4_text',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='PTC level 4 description'),
        ),
    ]
