# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_price_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsBSRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsrf', models.CharField(max_length=250)),
                ('brand_name', models.CharField(max_length=80)),
                ('strength', models.CharField(max_length=200, null=True)),
                ('route', models.CharField(max_length=20, null=True)),
                ('dosage_form', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubsGeneric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=120)),
                ('correction', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SubsManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=120)),
                ('correction', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SubsPTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=120)),
                ('correction', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SubsUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=120)),
                ('correction', models.CharField(max_length=120)),
            ],
        ),
    ]
