# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_price_calculator', '0002_subsbsrf_subsgeneric_subsmanufacturer_subsptc_subsunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendBSRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.PositiveIntegerField()),
                ('original', models.CharField(max_length=250)),
                ('brand_name', models.CharField(max_length=80)),
                ('strength', models.CharField(max_length=200, null=True)),
                ('route', models.CharField(max_length=20, null=True)),
                ('dosage_form', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendGeneric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.PositiveIntegerField()),
                ('original', models.CharField(max_length=150)),
                ('correction', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PendManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.PositiveIntegerField()),
                ('original', models.CharField(max_length=150)),
                ('correction', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PendPTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.PositiveIntegerField()),
                ('original', models.CharField(max_length=150)),
                ('correction', models.CharField(max_length=150)),
            ],
        ),
    ]
