# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_price_calculator', '0003_pendbsrf_pendgeneric_pendmanufacturer_pendptc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendbsrf',
            name='url',
        ),
        migrations.RemoveField(
            model_name='pendgeneric',
            name='url',
        ),
        migrations.RemoveField(
            model_name='pendmanufacturer',
            name='url',
        ),
        migrations.RemoveField(
            model_name='pendptc',
            name='url',
        ),
        migrations.AlterField(
            model_name='atcdescriptions',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='pendbsrf',
            name='original',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='pendgeneric',
            name='original',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='pendmanufacturer',
            name='original',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='pendptc',
            name='original',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='subsbsrf',
            name='bsrf',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='subsgeneric',
            name='original',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='subsmanufacturer',
            name='original',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='subsptc',
            name='original',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='subsunit',
            name='original',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
