# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_price_calculator', '0008_auto_20170920_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainformation',
            name='manufacturer',
            field=models.CharField(max_length=75),
        ),
    ]
