# Generated by Django 2.0.3 on 2018-05-30 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapart',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_parts', to='flash_cards.PartContainer'),
        ),
        migrations.AlterField(
            model_name='textpart',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_parts', to='flash_cards.PartContainer'),
        ),
    ]
