# Generated by Django 2.0.3 on 2018-05-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchingeAnswerPart',
            new_name='MatchingAnswerPart',
        ),
    ]
