# Generated by Django 2.0.3 on 2018-05-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmatchinganswer',
            name='question_container',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flash_cards.MatchingContainer'),
        ),
        migrations.AlterField(
            model_name='historicalsynonym',
            name='synonym_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='tag_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='matchinganswer',
            name='question_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash_cards.MatchingContainer'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='synonym_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
