# Generated by Django 2.0.3 on 2018-05-27 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0002_auto_20180527_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deck_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='historicaldeck',
            name='deck_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
