# Generated by Django 2.0.3 on 2018-05-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0002_historicalcard_historicalcarddeck_historicalcardfeedback_historicalcardtag_historicaldeck_historical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeformanswerpart',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='flash_cards/'),
        ),
        migrations.AlterField(
            model_name='freeformanswerpart',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfreeformanswerpart',
            name='media',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfreeformanswerpart',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmatchinganswerpart',
            name='media',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmatchinganswerpart',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmultiplechoiceanswerpart',
            name='media',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmultiplechoiceanswerpart',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalquestionpart',
            name='media',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalquestionpart',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrationalepart',
            name='media',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrationalepart',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='matchinganswerpart',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='flash_cards/'),
        ),
        migrations.AlterField(
            model_name='matchinganswerpart',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswerpart',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='flash_cards/'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswerpart',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionpart',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='flash_cards/'),
        ),
        migrations.AlterField(
            model_name='questionpart',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='rationalepart',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='flash_cards/'),
        ),
        migrations.AlterField(
            model_name='rationalepart',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
