# Generated by Django 2.0.3 on 2018-05-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0003_auto_20180530_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decktag',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='decktag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='historicaldecktag',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='historicaldecktag',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldecktag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='tags',
        ),
        migrations.DeleteModel(
            name='DeckTag',
        ),
        migrations.DeleteModel(
            name='HistoricalDeckTag',
        ),
    ]
