# Generated by Django 2.0.3 on 2018-05-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0004_auto_20180527_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='date_reviewed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldeck',
            name='date_reviewed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
