# Generated by Django 2.0.3 on 2018-05-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0007_auto_20180527_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalcard',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicaldeck',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
