# Generated by Django 2.0.3 on 2018-05-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0008_auto_20180527_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcard',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
