# Generated by Django 2.0.3 on 2018-05-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0010_auto_20180527_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmediapart',
            name='media_type',
            field=models.CharField(choices=[('a', 'Audio'), ('i', 'Image'), ('v', 'Video')], default='i', max_length=1),
        ),
        migrations.AlterField(
            model_name='mediapart',
            name='media_type',
            field=models.CharField(choices=[('a', 'Audio'), ('i', 'Image'), ('v', 'Video')], default='i', max_length=1),
        ),
    ]
