# Generated by Django 2.0.3 on 2018-05-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0013_auto_20180528_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rationale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_rationale', to='flash_cards.PartContainer', verbose_name='answer rationale'),
        ),
    ]
