# Generated by Django 2.0.3 on 2018-05-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0015_auto_20180528_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckstats',
            name='number_questions',
            field=models.IntegerField(default=0, verbose_name='number of questions'),
        ),
        migrations.AlterField(
            model_name='historicaldeckstats',
            name='number_questions',
            field=models.IntegerField(default=0, verbose_name='number of questions'),
        ),
    ]
