# Generated by Django 2.0.3 on 2018-05-29 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0018_auto_20180529_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='flash_cards.Tag'),
        ),
    ]
