# Generated by Django 2.0.3 on 2018-05-29 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0020_auto_20180529_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtag',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='flash_cards.Card'),
        ),
    ]
