# Generated by Django 2.0.3 on 2018-05-29 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0021_auto_20180529_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(through='flash_cards.CardTag', to='flash_cards.Tag'),
        ),
        migrations.AlterField(
            model_name='cardtag',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash_cards.Card'),
        ),
    ]
