# Generated by Django 2.0.3 on 2018-05-29 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0022_auto_20180529_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ManyToManyField(through='flash_cards.CardDeck', to='flash_cards.Deck'),
        ),
        migrations.AlterField(
            model_name='carddeck',
            name='card',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='flash_cards.Card'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carddeck',
            name='deck',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='flash_cards.Deck'),
            preserve_default=False,
        ),
    ]
