# Generated by Django 2.0.3 on 2018-05-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0023_auto_20180529_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='deck',
            new_name='decks',
        ),
    ]
