# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unqiue ID for this item', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title for the item', max_length=256)),
                ('date', models.DateField(auto_now_add=True, help_text='Date the play item was release')),
                ('type', models.CharField(choices=[('i', 'Image'), ('v', 'Video')], help_text='The file type of the item', max_length=1)),
            ],
            options={
                'ordering': ['date', 'title'],
            },
        ),
    ]
