# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_auto_20170827_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unqiue ID for this item', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title to display above the audio player', max_length=256, null=True)),
                ('type', models.CharField(default='a', editable=False, help_text='The file type of the item', max_length=1)),
                ('location', models.FileField(help_text='The uploaded audio content', upload_to='play/audio/')),
                ('description', models.TextField(help_text='Any additional text to display below the image', null=True)),
                ('ordering', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audio',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PlayImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unqiue ID for this item', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title to display above the image', max_length=256, null=True)),
                ('type', models.CharField(default='i', editable=False, help_text='The file type of the item', max_length=1)),
                ('location', models.ImageField(help_text='The uploaded image (high quality)', upload_to='play/images/original/')),
                ('alt_text', models.CharField(help_text='Text to show on cursor hover over the item', max_length=256, null=True)),
                ('description', models.TextField(help_text='Any additional text to display below the image', null=True)),
                ('ordering', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PlayPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the page', max_length=256)),
                ('date', models.DateField(auto_now_add=True, help_text='Date the play item was release')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.Category')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['date', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='playitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='PlayItem',
        ),
        migrations.AddField(
            model_name='playimage',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.PlayPage'),
        ),
        migrations.AddField(
            model_name='playaudio',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.PlayPage'),
        ),
    ]
