# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_auto_20170828_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playaudio',
            old_name='location',
            new_name='audio',
        ),
        migrations.AddField(
            model_name='playpage',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date to release this page on'),
        ),
        migrations.AlterField(
            model_name='playpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the play item was released'),
        ),
    ]
