# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_auto_20170828_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playimage',
            options={'ordering': ['ordering', 'title'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
