# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrhc_calendar', '0005_auto_20171005_1806'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftcode',
            unique_together=set([('code', 'user', 'role')]),
        ),
    ]
