# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrhc_calendar', '0007_auto_20171005_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='name',
            new_name='user',
        ),
    ]
