# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrhc_calendar', '0014_auto_20171016_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_code',
            field=models.ForeignKey(blank=True, help_text='The shift code for this shift', null=True, on_delete=django.db.models.deletion.CASCADE, to='rdrhc_calendar.ShiftCode'),
        ),
    ]
