# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrhc_calendar', '0015_auto_20171016_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendaruser',
            name='email',
        ),
    ]
