name: Django Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv run python -m pip install -U pip
        pipenv install --dev --ignore-pipfile
    - name: Setup Database
      run: |
        cp config/settings/.study_buffalo.env config/settings/study_buffalo.env
        psql -c "CREATE DATABASE study_buffalo;" -U postgres
        psql -c "CREATE USER study_buffalo WITH PASSWORD 'study_buffalo';" -U postgres
        psql -c "ALTER ROLE study_buffalo SET client_encoding TO 'utf8';" -U postgres
        psql -c "ALTER ROLE study_buffalo SET default_transaction_isolation TO 'read committed';" -U postgres
        psql -c "ALTER ROLE study_buffalo SET timezone TO 'UTC';" -U postgres
        psql -c "GRANT ALL PRIVILEGES ON DATABASE study_buffalo TO study_buffalo;" -U postgres
        psql -c "ALTER USER study_buffalo CREATEDB;" -U postgres
        pipenv run python manage.py collectstatic --no-input
    - name: Run Tests
      run: |
        pipenv run pytest --cov study_buffalo --cov-report xml
